before_commands:
    - "composer install --no-dev --prefer-source"
tools:
    external_code_coverage: true
    php_code_sniffer: 
        enabled: true
        filter:
            paths: ["src/*", "tests/*"]
        config:
            standard: "PSR2"
    php_sim:
        enabled: true
        filter:
            paths: ["src/*"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        filter:
            paths: ["src/*"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    sensiolabs_security_checker: true
