tools:
    php_code_sniffer: true
        filter:
            paths: ["src/*", "tests/*"]
        config:
            ruleset: phpcs.xml
    php_code_coverage:
        test_command: "phpunit -c tests/"
        filter:
            paths: ["src/*"]
    php_sim:
        enabled: true
        filter:
            paths: ["src/*"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        filter:
            paths: ["src/*"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
    sensiolabs_security_checker: true
