language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit --coverage-clover=coverage.clover
before_script: composer install
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
